_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.19.1
            "8":
                - 2
                - 5
            "12": 0.19.1
            "13": linux-x86_64
data:
    value:
        batch_size: 128
        dataset: cifar10
        num_workers: 4
        path: /home/groups/swl1/lhy/data/cifar10
        shuffle: true
model:
    value:
        ch: 64
        ch_mult:
            - 1
            - 2
            - 4
        image_size: 32
        in_channels: 3
        num_res_blocks: 1
        type: vae
        z_channels: 64
seed:
    value: 42
training:
    value:
        checkpoint_dir: /oak/stanford/groups/swl1/lhy/checkpoints/generative_models/vae_cifar10
        epochs: 100
        grad_clip: 1
        kl_weight: 0.00025
        learning_rate: 0.001
        log_interval: 100
        num_samples: 16
        sample_interval: 500
        save_interval: 10
        weight_decay: 0
wandb:
    value:
        entity: null
        log_model: false
        name: vae_cifar10
        project: generative-models
        tags:
            - vae
            - cifar10
